Hello World: Add missing step `npm install`
Otherwise `cds watch` fails with the error:

```
/Users/xxx/.nvm/versions/node/v18.15.0/lib/node_modules/@sap/cds-dk/lib/watch/livereload-server.js:24
        DEBUG?.(`live reload available at ${this.url}`)
               ^

TypeError: DEBUG is not a function
    at Server.listening (/Users/xxx/.nvm/versions/node/v18.15.0/lib/node_modules/@sap/cds-dk/lib/watch/livereload-server.js:24:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```