Typescript: add global installation of `tsx` earlier (#1761)
Following the documentation of setting up TypeScript, I ran into the
following issue:

```
$ cds watch

cds serve all --with-mocks --in-memory?
live reload enabled for browsers

        ___________________________

Error: detected C:\Users\...\cap-ts\tsconfig.json, but could not run with 'tsx'. Enable Typescript with
  npm install -D tsx typescript
```

Global installation is mentioned later within cds-tsx but if its also
required for `cds watch` it should be mentioned before already.

Therefore, my suggestion to add `tsx` to the other packages that should
be installed globally.


(Also it seems that the auto-generated tsconfig.json - when running `cds
add typescript` - is missing `compilerOptions.outDir`; otherwise VSCode
complains about `Cannot write file '.../cap-ts/eslint.config.mjs'
because it would overwrite input file.` but I guess that's a setup/code
issue and not a docs issue)