Correction of params (#1319)
The params variable seems to be an array these days and not an object.
If I try what is currently in the documentation I receive a `[cds] -
TypeError: this.params is not iterable`.

There might be other occurrences in this page that are therefore
incorrect, but I have not checked them.

Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>