Release PR  for July 2023 (#355)
* Add favicon and `apple-touch-icon` to Capire (#300)

* Fix hover color for anchors w/ code and Edit Link

* Add missing comma in code snippet (#327)

* Search: no fuzziness. More stop words

* Search: downrate Java MT classic page

* updated documentation about draft in node.js (#310)

* updated documentation about draft in node.js

* Update node.js/fiori.md

Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>

* Update node.js/fiori.md

Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>

* Update node.js/fiori.md

Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>

* Update node.js/fiori.md

Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>

* review fix

* cosmetics

* cosmetics

---------

Co-authored-by: D070615 <olena.timrova@sap.com>
Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>
Co-authored-by: manjunath <m.shankar@sap.com>

* Hello World: Add missing step `npm install` (#324)

Otherwise `cds watch` fails with the error:

```
/Users/xxx/.nvm/versions/node/v18.15.0/lib/node_modules/@sap/cds-dk/lib/watch/livereload-server.js:24
        DEBUG?.(`live reload available at ${this.url}`)
               ^

TypeError: DEBUG is not a function
    at Server.listening (/Users/xxx/.nvm/versions/node/v18.15.0/lib/node_modules/@sap/cds-dk/lib/watch/livereload-server.js:24:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Co-authored-by: Steffen Waldmann <steffen.waldmann@sap.com>

* hello-world: `cds add samples` is deprecated (#322)

* Various MTX-related changes (#320)

* Language

* Deprecation hint

* Move App-Router config to where it is actually required

* Mention pre-defined mock users more centrally

* No URL required in `cds pull` as in `cds push`

* punctuation

* Terminology

* Fix entity name in domain modeling sample (#330)

Wrong entity name associated to key project in Many-to-Many Association. It should be Projects :-)

* Add SSL verification error to HANA troubleshooting (#333)

* Add SSL verification error to HANA troubleshooting

Recently appeared in an internally reported issue.

* Typography

* Full examle for HANA `undeploy.json` (#326)

* `json` code fence
* Only `cds add hana`-created entries for `undeploy.json`

---------

Co-authored-by: Lothar Bender <lothar.bender@sap.com>

* Fix favicon base (#337)

* Add link for Node.js Lifecycle Events in cds-facade (#336)

* features: Postgres support for node.js (#299)

Co-authored-by: Daniel Hutzel <daniel.hutzel@sap.com>

* Clarify `undeploy.json` handling (#335)

* Fix for binding resolution in hybrid mode (#338)

Co-authored-by: Steffen Waldmann <steffen.waldmann@sap.com>

* make <> more prominent (#313)

* Cookbook.Overview only in navbar, not in sidebar (#346)

* Vitepress beta 7

* Exclude parked files

* Sitenmap: use built-in feature fron vitepress 7

* Use session context variables on SQLite and H2 (#331)

* Remove more deprecated properties

---------

Co-authored-by: Christian Georgi <chgeo@users.noreply.github.com>
Co-authored-by: Marc Becker <marc.becker@sap.com>

* Update CAP Java SDK to v2.1.0 (#344)

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

* Properly join URL parts

* Improve search ranking for title matches (#334)

* Allow words with 2 chars like `x4`
* Prefer terms with higher levels
* Move local search options

---------

Co-authored-by: Christian Georgi <christian.georgi@sap.com>
Co-authored-by: Christian Georgi <chgeo@users.noreply.github.com>

* TS types simplified for navbar massaging

* fix links to issues and prs (#349)

* default pool config not applicable for @cap-js databases (#314)

* default pool config not applicable for @cap-js databases

* cosmetics

---------

Co-authored-by: Mahati Shankar <m.shankar@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Revert "default pool config not applicable for @cap-js databases" (#350)

Revert "default pool config not applicable for @cap-js databases (#314)"

This reverts commit 4c852c602632bfc9113d8727eac2ddda56ddbc7e.

* Fixed Java security update (#347)

Update security.md

* correct spelling mistakes and add linting workflow (#352)

* Unrelease services.md (#323)

Update services.md

Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Default pool config not applicable for @cap js databases (#351)

* default pool config not applicable for @cap-js databases

* cosmetics

---------

Co-authored-by: sjvans <30337871+sjvans@users.noreply.github.com>

* Add `sqlite` and `h2` w/ new Maven goal (#325)

* Java Flavour of PostgreSQL guide (#273)

* Java Flavor of PostgreSQL guide

* touches

* Apply suggestions from code review

Co-authored-by: Marc Becker <marc.becker@sap.com>

* Update guides/databases-postgres.md

Co-authored-by: Marc Becker <marc.becker@sap.com>

* Update guides/databases-postgres.md

Co-authored-by: Marc Becker <marc.becker@sap.com>

* Update guides/databases-postgres.md

Co-authored-by: Marc Becker <marc.becker@sap.com>

* Apply suggestions from code review

Co-authored-by: Markus Ofterdinger <markus@ofterdinger.de>

* fix broken div

* Apply suggestions from code review

Co-authored-by: Markus Ofterdinger <markus@ofterdinger.de>

* Update persistence-services.md

* Update databases-postgres.md

* Use liquibase default locations

* touches

* Apply suggestions from code review

Co-authored-by: Markus Ofterdinger <markus@ofterdinger.de>

* Change the file names to sync with bookshop

* Fixed one more occurrence of schema.sql

* Small changes

* Feature is added

* Fix dead links

* Fix one more dead link

* Fix typos

* Move test container note

* Revert "Move test container note"

This reverts commit 8971c140410a9b432447945c5b812a5245e0aca8.

* Improve phrasing

* Added --profile pg to the cds deploy command

* Use right command

* Make command executable when copied

* Sync filenames with bookshop sample

* Minor adaptations regarding pg profile

* Show testcontainers hint only for Java

* cosmetics

* Minor fixes

---------

Co-authored-by: Marc Becker <marc.becker@sap.com>
Co-authored-by: Markus Ofterdinger <markus@ofterdinger.de>
Co-authored-by: René Jeglinsky <rene.jeglinsky@sap.com>
Co-authored-by: Vladimir Mikhaylenko <vladimir.mikhaylenko@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>
Co-authored-by: Mahati Shankar <m.shankar@sap.com>

* Order by alias example in Java section (#229)

* Order by alias example in Java section

* Identation

* Review suggestion

* Update java/query-api.md

Co-authored-by: René Jeglinsky <rene.jeglinsky@sap.com>

* Update java/query-api.md

---------

Co-authored-by: Adrian Görler <adrian.goerler@sap.com>
Co-authored-by: René Jeglinsky <rene.jeglinsky@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Clarify CQL injections (#317)

* Clarify CQL injections

* add js snippet

* Update aspects.md

* cosmetics

---------

Co-authored-by: Johannes Vogel <31311694+johannes-vogel@users.noreply.github.com>
Co-authored-by: Mahati Shankar <m.shankar@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Update docu for cds-compiler 4.1 (#332)

* Update docu for cds-compiler 4.1

- calc elem on-read may reference localized elem

* cosmetics

---------

Co-authored-by: Christian Georgi <chgeo@users.noreply.github.com>
Co-authored-by: Mahati Shankar <m.shankar@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Added BAS command to Getting Started (#340)

* Added BAS command to Getting Started

* cosmetics

---------

Co-authored-by: Mahati Shankar <m.shankar@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* Warn of incompatibility with Cloud SDK BOM (#329)

* Add warning to minimum versions

* Add hint to migration guide as well

* reformat and cosmetics

---------

Co-authored-by: Christian Georgi <chgeo@users.noreply.github.com>
Co-authored-by: Mahati Shankar <m.shankar@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>

* services is now inaccessible (#354)

* Calculated elements are not searchable by default (#343)

* Calculated elements are not searchable by default

* Rephrase

* Revert "Rephrase"

This reverts commit 11de5dbac83fa300076045c06312aa6ce2c3da92.

* Apply suggestion

* Ignore IDEA project

* Update guides/providing-services.md

Co-authored-by: Adrian Görler <adrian.goerler@sap.com>

* Added tip

* cosmetics

---------

Co-authored-by: Adrian Görler <adrian.goerler@sap.com>
Co-authored-by: Mahati Shankar <93712176+smahati@users.noreply.github.com>
Co-authored-by: Mahati Shankar <m.shankar@sap.com>

* Added link to Java installation guide (#341)

* Fiori Draft: add info on switching on fiori-draft-enabled (#342)

* Fiori Draft: add info on switching on fiori-draft-enabled

Can only be switched on if texts entities don't contain entries.

* add reasoning

---------

Co-authored-by: Steffen Waldmann <steffen.waldmann@sap.com>
Co-authored-by: Christian Georgi <christian.georgi@sap.com>
Co-authored-by: Nico Schoenteich <nicolai.schoenteich@sap.com>
Co-authored-by: Olena <etimryaka@gmail.com>
Co-authored-by: D070615 <olena.timrova@sap.com>
Co-authored-by: Dr. David A. Kunz <david.kunz@sap.com>
Co-authored-by: Pierre Fritsch <PierreFritsch@users.noreply.github.com>
Co-authored-by: Tim Schulze-Hartung <108271660+tim-sh@users.noreply.github.com>
Co-authored-by: Chiara De Dominicis <89581177+ChiaraDeDominicis-Reg@users.noreply.github.com>
Co-authored-by: Lothar Bender <lothar.bender@sap.com>
Co-authored-by: Christian Schürings <christian.schuerings@sap.com>
Co-authored-by: simonoswald <126768147+simonoswald@users.noreply.github.com>
Co-authored-by: Daniel Hutzel <daniel.hutzel@sap.com>
Co-authored-by: Manuel Fink <123368068+finkmanAtSap@users.noreply.github.com>
Co-authored-by: Johannes Vogel <31311694+johannes-vogel@users.noreply.github.com>
Co-authored-by: Christian Georgi <chgeo@users.noreply.github.com>
Co-authored-by: Adrian Görler <adrian.goerler@sap.com>
Co-authored-by: Marc Becker <marc.becker@sap.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Keckl, Matthias <127967727+MatthiasAtSAP@users.noreply.github.com>
Co-authored-by: sjvans <30337871+sjvans@users.noreply.github.com>
Co-authored-by: BraunMatthias <59841349+BraunMatthias@users.noreply.github.com>
Co-authored-by: René Jeglinsky <rene.jeglinsky@sap.com>
Co-authored-by: Markus Ofterdinger <markus@ofterdinger.de>
Co-authored-by: Vladimir Mikhaylenko <vladimir.mikhaylenko@sap.com>
Co-authored-by: Vladimir <niemda@me.com>
Co-authored-by: Steffen Weinstock <79531202+stewsk@users.noreply.github.com>